// <auto-generated />
using APIColoresDaltonicos.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIColoresDaltonicos.Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317192109_AgregadaConfiguracionDaltonismo")]
    partial class AgregadaConfiguracionDaltonismo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIColoresDaltonicos.Models.ConfiguracionDaltonismos.ConfiguracionDaltonismo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Correccion")
                        .HasColumnType("int");

                    b.Property<string>("TipoDaltonismo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("ConfiguracionesDaltonismo");
                });

            modelBuilder.Entity("APIColoresDaltonicos.Models.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("APIColoresDaltonicos.Models.ConfiguracionDaltonismos.ConfiguracionDaltonismo", b =>
                {
                    b.HasOne("APIColoresDaltonicos.Models.Usuarios.Usuario", "Usuario")
                        .WithOne("ConfiguracionDaltonismo")
                        .HasForeignKey("APIColoresDaltonicos.Models.ConfiguracionDaltonismos.ConfiguracionDaltonismo", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("APIColoresDaltonicos.Models.Usuarios.Usuario", b =>
                {
                    b.Navigation("ConfiguracionDaltonismo");
                });
#pragma warning restore 612, 618
        }
    }
}
